# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kakao' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kakao
  pod 'RxKakaoSDKAuth'  # 카카오 로그인
  pod 'RxKakaoSDKUser'  # 사용자 관리

end
